
modLoader="javafml"
loaderVersion="[37,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
issueTrackerURL="https://github.com/HexagonNico/BuzzyDrones/issues"

[[mods]]
    modId="buzzydrones"
    version="2.0.2"
    displayName="Buzzy Drones"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/buzzy-drones"
    logoFile="BuzzyDrones.png"
    #credits=""
    authors="HexagonNico"
    description="A mod that adds bee-drones to transport items"

[[dependencies.buzzydrones]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.buzzydrones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="AFTER"
    side="BOTH"
